---
- name: creating subnet
  ec2_vpc_subnet:
          state: present
          region: us-east-1
          vpc_id: "{{ vpc.vpc.id }}"
          cidr: 10.0.0.0/24
          resource_tags:  
            Name: lncsub
          az: us-east-1a
  register: subnet
- debug:
        msg: "{{ subnet.subnet.id }}"
