---
- name: "Launching EC2 instance"
  ec2:
   key_name: lncdemo
   instance_type: t2.micro
   image: ami-0ac019f4fcb7cb7e6
   group: lncsg
   vpc_subnet_id: "{{ subnet.subnet.id }}"
   assign_public_ip: yes
   user_data: "{{ lookup('file', 'docker.sh') }}"
   wait: true
   region: us-east-1
   instance_tags:
      Name: lncinstance
   exact_count: 1
   count_tag:
    Name: lncinstance
  register: ec2
- debug:
         msg: "{{ ec2 }}"

